### ISSUE TITLE
User profile picture placeholder issue

### ISSUE THREAD

**Issue by alexpunct** [alexpunct/chatgpt-journal#17]
Currently if the user doesn't have an avatar set, in the header there's a broken image being displayed. We should display a generic image instead.

**Comment by kaushikc44** [comment]
Can you please specify the file will try to do it.

**Comment by alexpunct** [comment]
> Can you please specify the file will try to do it.

Sure, you can find it in `src/lib_skeleton/AppBar/AppBar.svelte`

**Comment by kaushikc44** [comment]
Hi I have couple of questions regarding the Superbase as its mentioned I have to use that , and I haven't previously worked with it so . I have the URL and the secret key, where exactly am I suppose to put those ? Sorry I am beginner about it

**Comment by kaushikc44** [comment]
I set up exactly how the doc mentioned, yet I am getting an error.

**Comment by alexpunct** [comment]
> I set up exactly how the doc mentioned, yet I am getting an error.

Did you setup this project or the example in the documentation? You also need to run the migrations in the `supabase` folder on this repo.

**Comment by kaushikc44** [comment]
Let me try I will try to figure this out using my application and then probably try sorry I haven't touched svelt also haven't done any open source contribution.

**Comment by alexpunct** [comment]
@kaushikc44 I'm picking this one up as it needs to be fixed asap
